export const images = {
  gradientBackground: require('./gradientBackground.png'),
  grassBackground: require('./grassBackground.jpg'),
  subscribeCardBackground: require('./subscribeCardBackground.png'),
  videoSetupBackground: require('./videoSetupBackground.png'),
  AITools: require('./AITools.png'),
  AIToolThumbnail: require('./AIToolThumbnail.png'),
  aroundGreen: require('./aroundGreen.png'),
  fundamentals: require('./fundamentals.png'),
  golfFitness: require('./golfFitness.png'),
  mechanics: require('./mechanics.png'),
  mentalGame: require('./mentalGame.png'),
  offTheFairway: require('./offTheFairway.png'),
  offTheTee: require('./offTheTee.png'),
  onTheGreen: require('./onTheGreen.png'),
  shortGame: require('./shortGame.png'),
};
