export const images = {
  gradientBackground: require('./gradientBackground.png'),
  grassBackground: require('./grassBackground.jpg'),
  subscribeCardBackground: require('./subscribeCardBackground.png'),
  videoSetupBackground: require('./videoSetupBackground.png'),
  AIToolThumbnail: require('./AIToolThumbnail.png'),
  AITools: require('./golftips/AITools.png'),
  aroundGreen: require('./golftips/aroundGreen.png'),
  fundamentals: require('./golftips/fundamentals.png'),
  golfFitness: require('./golftips/golfFitness.png'),
  mechanics: require('./golftips/mechanics.png'),
  mentalGame: require('./golftips/mentalGame.png'),
  offTheFairway: require('./golftips/offTheFairway.png'),
  offTheTee: require('./golftips/offTheTee.png'),
  onTheGreen: require('./golftips/onTheGreen.png'),
  shortGame: require('./golftips/shortGame.png'),
};
