image: maven:3-openjdk-11 # Or newer

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &unit-tests
        name: Run Unit Tests
        image: node:16
        script:
          - yarn
          - yarn test
        artifacts:
          - coverage/**
    - step: &sonar-cloud
        size: 2x
        name: SonarCloud Scan
        script:
          - pipe: sonarsource/sonarcloud-scan:1.4.0
            variables:
              SONAR_SCANNER_OPTS: >
                -Dsonar.sources=src
                -Dsonar.javascript.node.maxspace=4096
                -Dsonar.javascript.coveragePlugin=jest
                -Dsonar.javascript.lcov.reportPaths=coverage/lcov-report/*.lcov
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

services:
  docker:
    memory: 4048

pipelines:
  pull-requests:
    '**':
      - step: *unit-tests
      - step: *sonar-cloud
  branches:
    dev:
      - step: *unit-tests
      - step: *sonar-cloud
    main:
      - step: *unit-tests
      - step: *sonar-cloud
