image: maven:3-openjdk-11 # Or newer

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &unit-tests
      name: Run Unit Tests
      script:
        - yarn
        - yarn test
      artifacts:
        - coverage/**
    - step: &sonar-cloud
        size: 2x
        name: SonarCloud Scan
        script:
          - pipe: sonarsource/sonarcloud-scan:1.4.0
            variables:
              EXTRA_ARGS: -Dsonar.sources=src
              SONAR_SCANNER_OPTS: >
                -Dsonar.javascript.node.maxspace=4096
                -Dsonar.tests=src
                -Dsonar.javascript.coveragePlugin=jest
                -Dsonar.testExecutionReportPaths=coverage/test-reporter.xml
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
pipelines:
  pull-requests:
    '**':
    - step: *unit-tests
    - step: *sonar-cloud
  branches:
    dev:
      - step: *unit-tests
      - step: *sonar-cloud
    main:
      - step: *unit-tests
      - step: *sonar-cloud
