version: 2.1

orbs:
  android: circleci/android@2.3.0
  node: circleci/node@5.1.0

jobs:
  android-dev-firebase:
    docker:
      - image: cimg/android:2023.06.1-node
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.18.1'
      - run: yarn
      - android/decode-keystore:
          keystore-location: android/app/keystore
      - run:
          name: Create keystore.properties
          command:
            cd android && printf 'releaseKeyAlias=%s\nreleaseKeyPassword=%s\nreleaseKeyStore=android/app/keystore\nreleaseStorePassword=%s' \
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_STORE_PASSWORD > keystore.properties
      - android/create-keystore-properties:
          working-directory: android
          release-keystore: android/app/keystore
      - android/fastlane-deploy:
          working-directory: android
          lane-name: firebase_deploy_dev

workflows:
  android-firebase-deploy-dev:
    jobs:
      - deploy-dev-android:
          type: approval

      - android-dev-firebase:
          requires:
            - deploy-dev-android
