version: 2.1

orbs:
  android: circleci/android@2.3.0
  node: circleci/node@5.1.0

jobs:
  android-dev-firebase:
    docker:
      - image: cimg/android:2023.06.1-node
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.18.1'
      - run: yarn
      - android/decode-keystore:
          keystore-location: android/app/keystore
      - run:
          name: Create keystore.properties
          command: cd android && printf 'keyAlias=%s\nkeyPassword=%s\nstoreFile=keystore\nstorePassword=%s' \
            $RELEASE_KEY_ALIAS $RELEASE_KEY_PASSWORD $RELEASE_STORE_PASSWORD > keystore.properties
      - run:
          name: Create fastlane env
          command: cd android/fastlane && printf 'FIREBASE_TOKEN=%s\nFIREBASE_APP_ID=%s\nFIREBASE_TESTERS_GROUP=%s' \
            $FIREBASE_TOKEN $FIREBASE_APP_ID $FIREBASE_TESTERS_GROUP > .env
      - run:
          name: Create Application env
          command: printf 'BASE_URL=%s' $BASE_URL_DEV > .env
      - android/fastlane-deploy:
          working-directory: android
          lane-name: firebase_deploy_dev

workflows:
  android-firebase-deploy-dev:
    jobs:
      - deploy-dev-android:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          type: approval

      - android-dev-firebase:
          requires:
            - deploy-dev-android

      - deploy-prod-android:
          requires:
            - android-dev-firebase
          type: approval
