import { VideoMetaData } from '@sz/models';

export const dummyVideoData: VideoMetaData[] = [
  {
    id: 'id',
    userId: 'string',
    name: 'string',
    videoUrl: 'string',
    videoType: 'Face View',
    thumbnailUrl: 'https://i.ibb.co/XFvHx8J/Rectangle-132.png',
    grading: 8,
    createdAt: '2023-06-04T13:22:29.181Z',
  },
  {
    id: 'id2',
    userId: 'string',
    name: 'string',
    videoUrl: 'string',
    videoType: 'Down The Line',
    thumbnailUrl: 'https://i.ibb.co/XFvHx8J/Rectangle-132.png',
    grading: 4,
    createdAt: '2023-06-04T13:22:29.181Z',
  },
  {
    id: 'id3',
    userId: 'string',
    name: 'string',
    videoUrl: 'string',
    videoType: 'Down The Line',
    thumbnailUrl: 'https://i.ibb.co/XFvHx8J/Rectangle-132.png',
    grading: 7,
    createdAt: '2023-06-04T13:22:29.181Z',
  },
  {
    id: 'id4',
    userId: 'string',
    name: 'string',
    videoUrl: 'string',
    videoType: 'Face View',
    thumbnailUrl: 'https://i.ibb.co/XFvHx8J/Rectangle-132.png',
    grading: 4.7,
    createdAt: '2023-06-04T13:22:29.181Z',
  },
  {
    id: 'id5',
    userId: 'string',
    name: 'string',
    videoUrl: 'string',
    videoType: 'Face View',
    thumbnailUrl: 'https://i.ibb.co/XFvHx8J/Rectangle-132.png',
    grading: 5.2,
    createdAt: '2023-06-04T13:22:29.181Z',
  },
];
