export enum Route {
  AnalysisTab = 'analysis-tab',
  AuthStack = 'auth-stack',
  ForgotPassword = 'forgot-password',
  HomeTab = 'home-tab',
  InfoStack = 'info-stack',
  LibraryTab = 'library-tab',
  Login = 'login',
  LoginStack = 'login-stack',
  MainStack = 'main-stack',
  MainBottomTabRoutesStack = 'main-bottom-tab-routes-stack',
  PlanDetails = 'plan-details',
  PricePlans = 'price-plans',
  PricePlansStack = 'price-plans-stack',
  PrivacyPolicy = 'privacy-policy',
  RegisterEmailVerification = 'register-email-verification',
  ResetPassword = 'reset-password',
  ResetPasswordEmailVerification = 'reset-password-email-verification',
  Signup = 'sign-up',
  SignupStack = 'signup-stack',
  TermsOfUse = 'terms-of-use',
  UploadVideoTab = 'upload-video-tab',
  VideosTab = 'videos-tab',
}
