export enum Route {
  AboutUs = 'about-us',
  AnalysisTab = 'analysis-tab',
  AuthStack = 'auth-stack',
  ContactUs = 'contact-us',
  Followers = 'followers',
  ForgotPassword = 'forgot-password',
  HomeTab = 'home-tab',
  InfoStack = 'info-stack',
  LibraryTab = 'library-tab',
  Login = 'login',
  LoginStack = 'login-stack',
  MainBottomTabRoutesStack = 'main-bottom-tab-routes-stack',
  MainDrawerRoutesStack = 'main-drawer-routes-stack',
  MainStack = 'main-stack',
  Notification = 'notification',
  PrivacyPolicy = 'privacy-policy',
  ProfileSettings = 'profile-settings',
  RegisterEmailVerification = 'register-email-verification',
  ResetPassword = 'reset-password',
  ResetPasswordEmailVerification = 'reset-password-email-verification',
  Signup = 'sign-up',
  SignupStack = 'signup-stack',
  TermsOfUse = 'terms-of-use',
  UploadVideoTab = 'upload-video-tab',
  VideosTab = 'videos-tab',
}
