export const FRAMES_PER_SECOND = 1;
export const FRAME_SCALE = 80;
export const FRAME_HEIGHT = 80;
export const FRAME_WIDTH = FRAME_SCALE / 2;
export const DURATION_WINDOW_DURATION = 4;
export const DURATION_WINDOW_WIDTH = DURATION_WINDOW_DURATION * FRAMES_PER_SECOND * FRAME_WIDTH;
export const POPLINE_POSITION = '50%';
